AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Perform AWS CodePipeline approval action from Slack

Parameters:
  SlackUri:
    Type: String
    Description: "Your slack app incoming webhook URI"
  PipelineName:
    Type: String
    Description: "CodePipeline pipeline name"
  TimeZone:
    Type: String
    Description: "TimeZone in your country. e.g. Asia/Tokyo"
    Default: UTC

Metadata:
  AWS::ServerlessRepo::Application:
    Name: CodePipelineSlackApprover
    Description: Perform AWS CodePipeline approval action from Slack
    Author: ykarakita
    HomePageUrl: https://github.com/ykarakita/code-pipeline-slack-approver
    SourceCodeUrl: https://github.com/ykarakita/code-pipeline-slack-approver
    ReadmeUrl: README.md
    SpdxLicenseId: MIT
    LicenseUrl: LICENSE
    Labels:
      - CodePipeline
      - Slack

Resources:
  NotifyApprovalAction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./target/app.zip
      Handler: app/notify_approval_action.handler
      Runtime: ruby2.7
      Description: Subscribe CodePipeline Approval action and notify.
      MemorySize: 128
      Timeout: 3
      Environment:
        Variables:
          SLACK_URI: !Ref SlackUri
      Events:
        SNS:
          Type: SNS
          Properties:
            Topic: !Ref CodePipelineApprovalActionTopic
      Policies:
        - AWSLambdaExecute
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - codepipeline:GetPipelineState
                - codepipeline:GetPipelineExecution
              Resource:
                - !Sub "arn:aws:codepipeline:${AWS::Region}:${AWS::AccountId}:${PipelineName}"
  ApprovalResultCallback:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./target/app.zip
      Handler: app/approval_result_callback.handler
      Runtime: ruby2.7
      Description: Performe CodePipeline Approval action.
      MemorySize: 128
      Timeout: 3
      Environment:
        Variables:
          TZ: !Ref TimeZone
      Events:
        Api:
          Type: Api
          Properties:
            Path: /approve
            Method: post
      Policies:
        - AWSLambdaExecute
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - codepipeline:PutApprovalResult
              Resource:
                - !Sub "arn:aws:codepipeline:${AWS::Region}:${AWS::AccountId}:${PipelineName}/*"
  CodePipelineApprovalActionTopic:
    Type: 'AWS::SNS::Topic'
    Properties:
      TopicName: !Ref AWS::StackName

Outputs:
  ServiceEndpoint:
    Description: Register this URL to Slack Interactive Components Request URL
    Value:
      Fn::Join:
        - ''
        - - https://
          - Ref: ServerlessRestApi
          - ".execute-api."
          - Ref: AWS::Region
          - ".amazonaws.com/Prod/approve"
